export const themeColor = 'green';
export const themeBackgroundColor = 'green';
export const logo = '/assets/images/your-care.png';
export const shortLogo = '';
export const adminAPI = '/api/v1/admin';
export const vendorAPI = '/api/v1/vendor';
export const publicAPI = '/api/v1';
export const doctorAPI = '/api/v1/doctor';
export const apiKey = 'eW91ckNhcmVAMzQ1NDYuI3NlY3VyZWQ/ZGF0YV9mb3JBUEk=';
