version: '3'
services:
    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    node-app:
        build: .
        volumes:
            - ./:/app:ro
            - /app/node_modules
        environment:
            - PORT:8080
